name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: Watremons/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 35ecea99c03911d62b9bf7b2b9a86e3e
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
